Repository artsy/cohesion, pull requests merged in 2020-11, with the labels that each got.

#119 Track sale_screen_load_complete
  src/Schema/Events/System.ts
  src/Schema/Events/index.ts
Labels: Version: Minor

#121 Add tapped_register_to_bid event
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#117 [AS-1656] Adds new search events
  src/Schema/Events/Search.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#122 Add context module for aboutThisAuction
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#123 Add liveAuctionRoom context module
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#124 feat: added tapped register to bid helper
  src/Helpers/Tap/TappedRegisterToBid.ts
  src/Helpers/Tap/__tests__/TappedRegisterToBid.test copy.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#125 fix: export tapped register to bid
  src/Helpers/index.ts
Labels: Version: Minor

#126 Fix/add saleinformation to owner types
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#128 [AS-1689] Adds clickedAppDownload event
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
Labels: Version: Minor

#96 Add helpers for ClickedArtworkGroup
  src/Helpers/Click/ClickedArtworkGroup.ts
  src/Helpers/Click/__tests__/ClickedArtworkGroup.test.ts
  src/Helpers/index.ts
  src/Schema/index.ts
Labels: Version: Minor

#127 Filter and sort tracking
  src/Schema/Events/FilterAndSort.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, canary

#130 add helper commercialFilterParamsChanged
  src/Helpers/FilterAndSort/CommercialFilterParamsChanged.ts
  src/Helpers/FilterAndSort/__tests__/CommercialFilterParamsChanged.ts
  src/Helpers/index.ts
  src/Schema/index.ts
Labels: Version: Minor, canary

#129 feat: Add /Consign tracking helpers + eslint autofixers
  .eslintrc.js
  .vscode/settings.json
  package.json
  src/Helpers/Click/ClickedAppDownload.ts
  src/Helpers/Click/ClickedArticleGroup.ts
  src/Helpers/Click/ClickedArtworkGroup.ts
  src/Helpers/Click/__tests__/ClickedArtistSeriesGroup.test.ts
  src/Helpers/Click/__tests__/ClickedArtworkGroup.test.ts
  src/Helpers/Click/__tests__/ClickedCollectionGroup.test.ts
  src/Helpers/Click/__tests__/ClickedEntityGroup.test.ts
  src/Helpers/Click/__tests__/ClickedMainArtworkGrid.test.ts
  src/Helpers/SavesAndFollows/Follow.ts
  src/Helpers/Search/FocusedOnSearchInput.ts
  src/Helpers/Search/SearchedWithNoResults.ts
  src/Helpers/Search/SelectedItemFromSearch.ts
  src/Helpers/Tap/TappedTabBar.ts
  src/Helpers/Tap/__tests__/TappedEntityGroup.test.ts
  src/Helpers/Tap/__tests__/TappedMainArtworkGrid.test.ts
  src/Helpers/index.ts
  src/Schema/Events/Authentication.ts
  src/Schema/Events/Click.ts
  src/Schema/Events/FilterAndSort.ts
  src/Schema/Events/SavesAndFollows.ts
  src/Schema/Events/Search.ts
  src/Schema/Events/System.ts
  src/Schema/Events/Tap.ts
  src/Schema/Events/Toggle.ts
  src/Schema/Events/index.ts
  yarn.lock
Labels: Version: Minor

#131 Track add_to_calendar event
  src/Schema/Events/AddToCalendar.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#118 [AS-1657] Adds onboarding event
  src/Schema/Events/Authentication.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#135 #trivial: Add to calendar helper
  src/Helpers/AddToCalendar.ts
  src/Helpers/index.ts
  src/Schema/Events/AddToCalendar.ts
  src/Schema/Events/Authentication.ts
  src/Schema/index.ts
Labels: Merge On Green

#134 Add new events and contexts for auction results on iOS
  src/Schema/Events/FilterAndSort.ts
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#138 #trivial: Add user to OwnerTypes
  src/Schema/Values/OwnerType.ts
Labels: Merge On Green, Version: Minor
