Repository artsy/cohesion, pull requests merged in 2020-12, with the labels that each got.

#139 Track critical myCollection events and contexts
  src/Schema/Events/MyCollection.ts
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#143 feat: helpers for My Collection tracking events
  src/Helpers/MyCollection/AddCollectedArtwork.ts
  src/Helpers/MyCollection/DeleteCollectedArtwork.ts
  src/Helpers/MyCollection/EditCollectedArtwork.ts
  src/Helpers/MyCollection/TappedCollectedArtwork.ts
  src/Helpers/MyCollection/__tests__/AddCollectedArtwork.test.ts
  src/Helpers/MyCollection/__tests__/DeleteCollectedArtwork.test.ts
  src/Helpers/MyCollection/__tests__/EditCollectedArtwork.test.ts
  src/Helpers/MyCollection/__tests__/TappedCollectedArtwork.test.ts
  src/Helpers/Tap/TappedInfoBubble.ts
  src/Helpers/Tap/TappedSell.ts
  src/Helpers/Tap/__tests__/TappedInfoBubble.test.ts
  src/Helpers/Tap/__tests__/TappedRegisterToBid.test.ts
  src/Helpers/Tap/__tests__/TappedSell.test.ts
  src/Schema/Events/MyCollection.ts
Labels: Jira Synced, Version: Minor

#141 Tracked events for inbox on iOS
  src/Schema/Events/Conversations.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/OwnerType.ts
  src/Schema/Values/Tab.ts
Labels: Version: Minor

#144 feat: export my collection helpers
  src/Helpers/index.ts
Labels: Merge On Green, Version: Patch

#142 Track screen views
  src/Schema/Events/System.ts
  src/Schema/Events/index.ts
Labels: Version: Minor

#152 feat: helper for tappedCollectedArtworkImages
  src/Helpers/MyCollection/TappedCollectedArtwork.ts
  src/Helpers/MyCollection/TappedCollectedArtworkImages.ts
  src/Helpers/MyCollection/__tests__/TappedCollectedArtworkImages.test.ts
  src/Helpers/index.ts
Labels: Merge On Green

#154 chore: synchronize TappedCollectedArtwork helper API with schema
  src/Helpers/MyCollection/TappedCollectedArtwork.ts
Labels: Merge On Green

#155 add my collection modules, asdf versions file #trivial
  .tool-versions
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor
