Repository artsy/cohesion, pull requests merged in 2020-08, with the labels that each got.

#88 Add "artists" and "galleries" to OwnerType
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#85 Add tappedMainArtworkGrid helper
  src/Helpers/Tap/TappedMainArtworkGrid.ts
  src/Helpers/Tap/__tests__/TappedMainArtworkGrid.test.ts
  src/Schema/Events/Tap.ts
Labels: Version: Minor

#91 Adds export for tapped artwork grid + owner type for artist series
  src/Helpers/Tap/TappedMainArtworkGrid.ts
  src/Helpers/index.ts
  src/Schema/Values/OwnerType.ts
Labels: Merge On Green, Version: Minor

#92 Include artistSeries in ScreenOwnerType
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#90 [AS-1437] Artist series analytics tracking for iOS and web
  src/Schema/Events/Click.ts
  src/Schema/Events/SavesAndFollows.ts
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#95 Use auth context for follow
  src/Helpers/SavesAndFollows/Follow.ts
  src/Schema/Events/SavesAndFollows.ts
Labels: Version: Minor

#97 Add article and articles to OwnerType
  src/Schema/Values/OwnerType.ts
Labels: Merge On Green, Version: Minor

#99 Adds allArtistSeries for iOS
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#98 FollowedGene / UnfollowedGene
  src/Helpers/SavesAndFollows/Follow.ts
  src/Helpers/SavesAndFollows/__tests__/Follow.test.ts
  src/Schema/Events/SavesAndFollows.ts
  src/Schema/Events/index.ts
Labels: Version: Patch
