Repository artsy/cohesion, pull requests merged in 2020-04, with the labels that each got.

#15 Update auction results tracking strings
  src/Schema/Authentication.ts
Labels: Jira Synced, Version: Minor

#16 Adds createdAccount and successfullyLoggedIn to Schema
  src/Schema/ActionType.ts
  src/Schema/Authentication.ts
  src/Schema/Event.ts
Labels: Version: Patch

#12 Add Typedoc static site
  .circleci/config.yml
  .gitignore
  README.md
  package.json
  src/Events/AuthImpression.ts
  src/Events/index.ts
  src/Schema/ActionType.ts
  src/Schema/Authentication.ts
  src/Schema/ContextModule.ts
  src/Schema/Event.ts
  src/Schema/index.ts
  tsconfig.json
  yarn.lock
Labels: Version: Trivial

#17 Add CreatedAccount and SuccessfullyLoggedIn events
  src/Events/Authentication/AuthImpression.ts
  src/Events/Authentication/CreatedAccount.ts
  src/Events/Authentication/SuccessfullyLoggedIn.ts
  src/Events/Authentication/Typings.ts
  src/Events/Authentication/__tests__/AuthImpression.test.ts
  src/Events/Authentication/__tests__/CreatedAccount.test.ts
  src/Events/Authentication/__tests__/SuccessfullyLoggedIn.test.ts
  src/Events/index.ts
  src/Schema/Event.ts
Labels: Version: Minor

#20 Remove module resolver
  .babelrc
  package.json
  src/Events/Authentication/AuthImpression.ts
  src/Events/Authentication/CreatedAccount.ts
  src/Events/Authentication/SuccessfullyLoggedIn.ts
  src/Events/Authentication/Typings.ts
  src/Events/Authentication/__tests__/AuthImpression.test.ts
  src/Events/Authentication/__tests__/CreatedAccount.test.ts
  src/Events/Authentication/__tests__/SuccessfullyLoggedIn.test.ts
  src/index.ts
  tsconfig.json
  yarn.lock
Labels: Version: Patch

#21 Auth events use triggerSeconds
  src/Events/Authentication/CreatedAccount.ts
  src/Events/Authentication/SuccessfullyLoggedIn.ts
  src/Events/Authentication/Typings.ts
  src/Events/Authentication/__tests__/CreatedAccount.test.ts
  src/Events/Authentication/__tests__/SuccessfullyLoggedIn.test.ts
Labels: Version: Patch

#30 Use typescript strict
  tsconfig.json
Labels: Version: Trivial

#24 Create iOS tapped group events and schema
  src/Schema/ActionType.ts
  src/Schema/ContextModule.ts
  src/Schema/Event.ts
  src/Schema/OwnerType.ts
Labels: Version: Patch

#31 improve file structure
  README.md
  src/Events/Authentication/AuthImpression.ts
  src/Events/Authentication/CreatedAccount.ts
  src/Events/Authentication/ResetYourPassword.ts
  src/Events/Authentication/SuccessfullyLoggedIn.ts
  src/Events/Authentication/__tests__/AuthImpression.test.ts
  src/Events/Authentication/__tests__/CreatedAccount.test.ts
  src/Events/Authentication/__tests__/ResetYourPassword.test.ts
  src/Events/Authentication/__tests__/SuccessfullyLoggedIn.test.ts
  src/Schema/ActionType.ts
  src/Schema/Authentication.ts
  src/Schema/ContextModule.ts
  src/Schema/Event.ts
  src/Schema/Events/Authentication.ts
  src/Schema/Events/Tap.ts
  src/Schema/Intent.ts
  src/Schema/index.ts
Labels: Version: Major
