Repository artsy/cohesion, pull requests merged in 2020-05, with the labels that each got.

#32 Tapped entity event helper
  src/Events/Tap/TappedEntityGroup.ts
  src/Events/Tap/__tests__/TappedEntityGroup.test.ts
  src/Events/index.ts
  src/Schema/OwnerType.ts
Labels: Version: Patch

#35 add export for TappedEntityDestinationType
  src/Events/Tap/TappedEntityGroup.ts
Labels: Version: Patch

#36 Add additional screen destinations, add category screen
  src/Events/Tap/TappedEntityGroup.ts
  src/Events/Tap/__tests__/TappedEntityGroup.test.ts
  src/Schema/OwnerType.ts
Labels: Version: Patch

#46 Add tappedConsign helper
  src/Events/Tap/TappedConsign.ts
  src/Events/Tap/__tests__/TappedConsign.test.ts
  src/Schema/Events/Tap.ts
Labels: Version: Patch

#48 Expose consign helpers
  src/Events/index.ts
Labels: Version: Minor

#47 Manage links in README
  README.md
Labels: Version: Minor

#49 Put NPM badge back
  README.md
Labels: Merge On Green, Version: Minor

#50 Don't require module height for entity group
  src/Events/Tap/TappedEntityGroup.ts
Labels: Version: Minor

#51 Fix broken build
  src/Schema/Events/Tap.ts
Labels: Merge On Green, Version: Minor

#52 Migrate from tslint to eslint
  .eslintignore
  .eslintrc.js
  .npmignore
  package.json
  src/Events/Authentication/CreatedAccount.ts
  src/Events/Authentication/ResetYourPassword.ts
  src/Events/Authentication/SuccessfullyLoggedIn.ts
  src/Events/Authentication/__tests__/AuthImpression.test.ts
  src/Events/Authentication/__tests__/CreatedAccount.test.ts
  src/Events/Authentication/__tests__/ResetYourPassword.test.ts
  src/Events/Tap/TappedEntityGroup.ts
  src/Events/Tap/__tests__/TappedEntityGroup.test.ts
  src/Schema/Event.ts
  tslint.json
  yarn.lock
Labels: Version: Trivial
