Repository artsy/cohesion, pull requests merged in 2020-06, with the labels that each got.

#55 Adds ClickedEntityGroup events
  src/Events/Tap/TappedConsign.ts
  src/Schema/ContextModule.ts
  src/Schema/EntityModuleType.ts
  src/Schema/Event.ts
  src/Schema/Events/Click.ts
  src/Schema/Events/Tap.ts
  src/Schema/index.ts
Labels: Version: Minor

#59 Add helper for TimeOnPage event
  src/Events/System/TimeOnPage.ts
  src/Events/index.ts
  src/Schema/index.ts
Labels: Merge On Green, Version: Minor

#60 add timeOnPage helper test
  src/Events/System/__tests__/TimeOnPage.test.ts
Labels: Merge On Green, Version: Trivial

#58 Adds clickedMainArtworkGrid
  src/Schema/Event.ts
  src/Schema/Events/Click.ts
Labels: Version: Minor

#61 Refactors clickedMainArtworkGrid
  src/Schema/Events/Click.ts
Labels: Version: Minor

#62 Clicked main artwork grid helper
  src/Events/Click/ClickedMainArtworkGrid.ts
  src/Events/Click/__tests__/ClickedMainArtworkGrid.test.ts
  src/Events/index.ts
Labels: Version: Minor

#63 @eessex => [OwnerType] Add collect page
  src/Schema/OwnerType.ts
Labels: Version: Minor

#64 Cleanup file structure
  README.md
  src/Helpers/Authentication/AuthImpression.ts
  src/Helpers/Authentication/CreatedAccount.ts
  src/Helpers/Authentication/ResetYourPassword.ts
  src/Helpers/Authentication/SuccessfullyLoggedIn.ts
  src/Helpers/Authentication/__tests__/AuthImpression.test.ts
  src/Helpers/Authentication/__tests__/CreatedAccount.test.ts
  src/Helpers/Authentication/__tests__/ResetYourPassword.test.ts
  src/Helpers/Authentication/__tests__/SuccessfullyLoggedIn.test.ts
  src/Helpers/Click/ClickedEntityGroup.ts
  src/Helpers/Click/ClickedMainArtworkGrid.ts
  src/Helpers/Click/__tests__/ClickedEntityGroup.test.ts
  src/Helpers/Click/__tests__/ClickedMainArtworkGrid.test.ts
  src/Helpers/System/TimeOnPage.ts
  src/Helpers/System/__tests__/TimeOnPage.test.ts
  src/Helpers/Tap/TappedConsign.ts
  src/Helpers/Tap/TappedEntityGroup.ts
  src/Helpers/Tap/__tests__/TappedConsign.test.ts
  src/Helpers/Tap/__tests__/TappedEntityGroup.test.ts
  src/Helpers/index.ts
  src/Schema/Events/Authentication.ts
  src/Schema/Events/Click.ts
  src/Schema/Events/System.ts
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/EntityModuleType.ts
  src/Schema/Values/Intent.ts
  src/Schema/Values/OwnerType.ts
  src/Schema/index.ts
  src/index.ts
Labels: Merge On Green, Version: Minor

#65 Cleanup docs links
  src/Schema/Events/Click.ts
  src/Schema/Events/Tap.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/EntityModuleType.ts
  src/Schema/Values/Intent.ts
  src/Schema/Values/OwnerType.ts
Labels: Merge On Green, Version: Minor

#66 typo
  src/Helpers/System/TimeOnPage.ts
  src/Helpers/System/__tests__/TimeOnPage.test.ts
Labels: Version: Trivial

#67 GALL-2880 Add tracking for signing up due to viewing rooms
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/Intent.ts
Labels: Version: Minor

#68 Events for conversations
  src/Schema/Events/Conversations.ts
  src/Schema/Events/index.ts
  src/Schema/index.ts
Labels: Version: Minor

#70 Add helpers for conversation events (PURCHASE-1896)
  src/Helpers/Conversations/FocusedOnConversationMessageInput.ts
  src/Helpers/Conversations/SentConversationMessage.ts
  src/Helpers/Conversations/__tests__/FocusedOnConversationMessageInput.test.ts
  src/Helpers/Conversations/__tests__/SentConversationMessage.test.ts
  src/Helpers/index.ts
  src/Schema/Events/Conversations.ts
Labels: Version: Minor

#69 Track taps on the iOS promo space
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor
