Repository artsy/cohesion, pull requests merged in 2021-03, with the labels that each got.

#169 [AS-1950] Inquiry checkout events
  src/Schema/Events/Conversations.ts
  src/Schema/Events/index.ts
  src/Schema/Values/OwnerType.ts
Labels: Jira Synced, Version: Minor

#168 [AS-1940] New Checklist Events in Cohesion
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#171 Add inquiry checkout tap event
  src/Helpers/Conversations/TappedMakeOffer.ts
  src/Helpers/Conversations/TappedViewOffer.ts
  src/Helpers/Conversations/__tests__/TappedMakeOffer.test.ts
  src/Helpers/Conversations/__tests__/TappedViewOffer.test.ts
  src/Helpers/index.ts
Labels: Jira Synced, Version: Minor

#173 Clarifies the use of helpers
  README.md
Labels: Version: Minor

#172 Chore(PX-3846): Clicked[Expand|Collapse]Arrow -> ClickedExpansionToggle
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
Labels: Jira Synced, Version: Minor

#175 Add artistAuctionResults owner
  src/Schema/Events/Tap.ts
  src/Schema/Values/OwnerType.ts
Labels: Jira Synced, Version: Minor

#174 Auction results filtering
  src/Schema/Events/FilterAndSort.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Jira Synced

#176 [AS-1992] Adds new auctions page tracking
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Jira Synced, Version: Minor
