Repository artsy/cohesion, pull requests merged in 2021-07, with the labels that each got.

#201 feat: add auctionResultsForArtistsYouFollow to OwnerType.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/OwnerType.ts
Labels: Jira Synced, Version: Minor

#204 chore: updates schema and tracking method for inquiry make offer screen
  src/Helpers/Conversations/TappedConfirmArtwork.ts
  src/Schema/Events/Conversations.ts
Labels: Jira Synced, Version: Minor

#206 fix: exports TappedConfirmArtwork
  src/Helpers/index.ts
Labels: Jira Synced, Merge On Green, Version: Minor

#196 [PX-4111] - Adds new shipping flow events to Cohesion
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#208 Added in trending Lots and standoutlots
  src/Schema/Values/ContextModule.ts
Labels: Jira Synced, Merge On Green, Version: Minor

#203 [PX-4220] - Track analytics for weight & framed dimensions in CMS
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#207 Event for Page change
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
Labels: Version: Minor

#211 Follow fair organizer Sign up modal Context module
  src/Schema/Values/ContextModule.ts
Labels: Jira Synced, Version: Minor
