Repository artsy/cohesion, pull requests merged in 2021-09, with the labels that each got.

#225 feature: Node 14 LTS
  .circleci/config.yml
  .nvmrc
  .tool-versions
Labels: Version: Major

#226 feature: Configure Dependabot Alerts
  .github/depdendabot.yml
Labels: Version: Trivial

#228 chore: Update Renovate User
  renovate.json
Labels: Version: Patch, Merge On Green

#234 feat: add google as auth service
  src/Schema/Events/Authentication.ts
Labels: Version: Minor, Jira Synced

#235 remove tappedInfoBubble helper
  src/DeprecatedHelpers/Tap/TappedInfoBubble.ts
  src/DeprecatedHelpers/Tap/__tests__/TappedInfoBubble.test.ts
  src/DeprecatedHelpers/index.ts
Labels: Version: Minor, Jira Synced, canary

#236 removed clickedArtworkGroup helper
  src/DeprecatedHelpers/Click/ClickedArtworkGroup.ts
  src/DeprecatedHelpers/Click/__tests__/ClickedArtworkGroup.test.ts
  src/DeprecatedHelpers/index.ts
Labels: Version: Minor, Jira Synced, canary

#239 Fixes to types for new inquiry
  src/DeprecatedHelpers/Authentication/CreatedAccount.ts
  src/DeprecatedHelpers/Authentication/ResetYourPassword.ts
  src/DeprecatedHelpers/Authentication/SuccessfullyLoggedIn.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#238 Sent inquiry
  src/Schema/Events/Conversations.ts
  src/Schema/Events/Inquiries.ts
  src/Schema/index.ts
Labels: Version: Minor

#240 Revert "Sent inquiry"
  src/Schema/Events/Conversations.ts
  src/Schema/Events/Inquiries.ts
  src/Schema/index.ts
Labels: Version: Minor

#242 feature: Add missing Home props
  src/Schema/Events/Conversations.ts
  src/Schema/Events/Inquiries.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/OwnerType.ts
Labels: canary
