Repository artsy/cohesion, pull requests merged in 2021-04, with the labels that each got.

#178 Chore: Change babel config
  .babelrc
  package.json
  yarn.lock
Labels: Version: Minor

#179 Adds Fair Items Event to CMS Checklist
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#180 chore: add label and remove type from ClickedEditArtwork
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
Labels: Version: Minor

#182 [WIP] feat: add tracking contextScreenOwnerType
  src/Helpers/Tap/TappedTabBar.ts
  src/Helpers/Tap/__tests__/TappedTabBar.test.ts
  src/Schema/Values/OwnerType.ts
Labels: Jira Synced, Version: Minor

#184 refactor(filter params): replace nested properties with a JSON string
  src/Helpers/FilterAndSort/CommercialFilterParamsChanged.ts
  src/Helpers/FilterAndSort/__tests__/CommercialFilterParamsChanged.ts
  src/Helpers/Tap/TappedTabBar.ts
  src/Schema/Events/FilterAndSort.ts
Labels: Jira Synced, Version: Major
