Repository artsy/cohesion, pull requests merged in 2022-05, with the labels that each got.

#315 Adds auctionPageView and documentation
  src/Schema/Events/Auction.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#327 [NX-3133] Adding impulse id to buy now tap
  src/Schema/Events/Conversations.ts
  src/Schema/Events/Tap.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced

#318 feat: adds schema for article events
  src/Schema/Events/Click.ts
  src/Schema/Events/Impression.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#328 fix: exposes impression
  src/Schema/Events/Conversations.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/OwnerType.ts
  src/Schema/index.ts
Labels: Version: Patch
