Repository artsy/cohesion, pull requests merged in 2022-03, with the labels that each got.

#306 feat: Add myCollectionComparableWorks context module
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor, Jira Synced

#302 chore: update dependabot reviewers
  .github/dependabot.yml
Labels: Version: Trivial

#307 remove tappedViewOffer helper
  src/DeprecatedHelpers/Conversations/TappedViewOffer.ts
  src/DeprecatedHelpers/Conversations/__tests__/TappedViewOffer.test.ts
  src/DeprecatedHelpers/index.ts
Labels: Version: Minor, Jira Synced

#304 adding experiment
  src/Schema/Events/ExperimentViewed.ts
  src/Schema/Events/index.ts
Labels: Jira Synced, canary

#309 fix: add missing export for ExperimentViewed
  src/Schema/index.ts
Labels: Version: Minor, Jira Synced

#310 feat(auction): Add auction events
  src/Schema/Events/Auction.ts
  src/Schema/Events/ExperimentViewed.ts
  src/Schema/Events/MyCollection.ts
  src/Schema/Events/index.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#311 chore: add ExperimentViewed to events
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#312 feat: Add tapped skip event
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#313 (GRO-834) add trove rail to context modules
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor, Jira Synced

#314 chore: add saved search/-es to PageOwnerType
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced

#316 feat(CX-2457): added TappedSellArtwork and TappedLearnMore events
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#317 feat(CX-2457): added myCollectionArtworkAbout context module
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor, Jira Synced

#321 feat: Add artworkRecommendationsRail context module
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor
