Repository artsy/cohesion, pull requests merged in 2023-01, with the labels that each got.

#384 feat(auth): adds scroll to auth trigger
  src/Schema/Events/Authentication.ts
Labels: Version: Minor

#386 feat: Add events for new MyC web uploading flow
  src/Schema/Events/MyCollection.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor, Jira Synced

#387 fix: Adjsut new My Collection event owner types
  src/Schema/Events/MyCollection.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#388 fix: Adjsut new My Collection event owner type
  src/Schema/Events/MyCollection.ts
Labels: Version: Minor

#389 fix: Adjust new My Collection event keys
  src/Schema/Events/MyCollection.ts
Labels: Version: Minor

#390 chore: update experiment_viewed event to requirements asked by analytics
  src/Schema/Events/ExperimentViewed.ts
  src/Schema/Events/index.ts
Labels: Version: Minor

#391 chore: add context module to ExperimentViewed
  src/Schema/Events/ExperimentViewed.ts
Labels: Version: Minor, Jira Synced, Squash On Green

#392 chore: add context owner screen to ExperimentViewed
  src/Schema/Events/ExperimentViewed.ts
Labels: Version: Minor, Jira Synced

#393 chore: add missing fields to ExperimentViewed
  src/Schema/Events/Click.ts
  src/Schema/Events/ExperimentViewed.ts
  src/Schema/Events/Tap.ts
Labels: Version: Minor, Jira Synced, Squash On Green
