Repository artsy/cohesion, pull requests merged in 2023-11, with the labels that each got.

#470 chore: Add createAlert to AuthContextModule
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#471 feat(ONYX-375): add ContextModule and OwnerType for alerts filters
  src/Schema/Events/Click.ts
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced, Squash On Green

#472 chore: remove TappedAddFilters event, modify ClickedAddFilters event
  src/Schema/Events/Click.ts
  src/Schema/Events/Search.ts
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
Labels: Version: Trivial, Jira Synced

#473 add OwnerType.alertConfirmation to PageOwnerType
  src/Schema/Values/OwnerType.ts
Labels: Version: Trivial, Jira Synced, Squash On Green
