Repository artsy/cohesion, pull requests merged in 2023-02, with the labels that each got.

#395 feat: add upcoming auctions results rail
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor, Jira Synced

#396 feat: add upcoming auctions OwnerType
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced

#397 feat: add curatedTrendingArtistsRail context module
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor, Jira Synced

#398 [AS-3677] CMS conversation page events
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#400 [AS-3677] Adding action type
  src/Schema/Events/Click.ts
Labels: Version: Minor, Jira Synced

#402 feat: Add curatorPicksRail context module
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#403 feat: add rail viewed event
  src/Schema/Events/ImpressionTracking.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced, Squash On Green

#404 feat: Add recentlyViewed owner type
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#401 chore: PX-5429 adding new events for BN and MO
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#405 feat: add auctionLotsEndingSoonRail context module
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor, Jira Synced, Squash On Green

#406 chore: add missing ImpressionTracking export to cohesion
  src/Schema/index.ts
Labels: Version: Minor, Jira Synced

#407 feat: ADd recentlyViewed to screen owner type
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#409 Adds tooltipViewed for progressive onboarding
  src/Schema/Events/ImpressionTracking.ts
  src/Schema/Events/index.ts
Labels: Version: Minor
