Repository artsy/cohesion, pull requests merged in 2023-03, with the labels that each got.

#410 feat: Add newWorksFromGalleriesYouFollow screen owner type
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#411 feat: add searchSuggestionQuickNavigationItemSelected event
  src/Schema/Events/Search.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#412 Feat(CX-3429): Add SWA ContextModules
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor, Jira Synced

#413 feat: Add similarToRecentlyViewed screen owner type
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#414 fix: Move similarToRecentlyViewed to ScreenOwnerType
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced, Squash On Green

#416 feat: add item viewed
  src/Schema/Events/ImpressionTracking.ts
  src/Schema/Events/Search.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#417 chore: add item type and id to ItemViewed
  src/Schema/Events/ImpressionTracking.ts
Labels: Version: Minor, Jira Synced

#419 [AS-3848] Adding new event for mark as sold
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#425 chore: downgrade typescript
  package.json
  yarn.lock
Labels: Version: Minor, Jira Synced
