Repository artsy/cohesion, pull requests merged in 2023-05, with the labels that each got.

#430 chore: make sale id optional for IDV
  src/Schema/Events/Click.ts
Labels: Version: Patch

#432 feat: adds schema for cookie consent manager
  src/Schema/Events/CookieConsent.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced, canary

#431 Event to track errors
  src/Schema/Events/ImpressionTracking.ts
  src/Schema/Events/index.ts
Labels: Version: Minor

#434 feat: Add galleriesForYou screen owner type
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced

#433 feat: add events schema for search pills
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor, Jira Synced
