Repository artsy/cohesion, pull requests merged in 2024-06, with the labels that each got.

#503 chore: Add new submission artwork form owner types
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#504 fix: Rename `artworkForm*` owner types to `submitArtworkStep*`
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Squash On Green

#505 feat: adds events for conversation history
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#506 feat: adds whats new context module
  src/DeprecatedSchema/DeprecatedValues.ts
Labels: Version: Minor

#507 Adding tracking for Complete your profile prompt on web and app
  src/Schema/Events/Click.ts
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced
