Repository artsy/cohesion, pull requests merged in 2024-10, with the labels that each got.

#532 feat(DIA-815): added "tap" to AuthTrigger
  src/Schema/Events/Authentication.ts
Labels: Version: Minor

#531 chore: Add more data to event when publishing matching work from demand AMBER-1090
  src/Schema/Events/Click.ts
Labels: Version: Minor

#533 feat(EMI-2098): Add tappedNotification and tappedClearNotification to the schema
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor, Jira Synced

#535 feat(DIA-863): add discoverSomethingNewSection and exploreBySection modules
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor, Jira Synced

#534 feat: update events definition to track update failed payments
  src/Schema/Events/Click.ts
  src/Schema/Events/ImpressionTracking.ts
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced

#536 feat(DIA-863): add tap events to the new home view cards
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced, Art Advisor

#537 fix: typo error
  src/Schema/Events/ImpressionTracking.ts
  src/Schema/Events/Tap.ts
Labels: Version: Minor, Jira Synced
