Repository artsy/cohesion, pull requests merged in 2024-01, with the labels that each got.

#478 chore(ONYX-535): Clean up analytic events related to TinEye (reverse image) search
  src/Schema/Events/ReverseImageSearch.ts
  src/Schema/Events/index.ts
  src/Schema/Values/OwnerType.ts
  src/Schema/index.ts
Labels: Version: Minor, Jira Synced

#479 [AS-4346] Adding new events for partners offers
  src/Schema/Events/Click.ts
  src/Schema/Events/ImpressionTracking.ts
  src/Schema/Events/index.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced

#481 feat: Add page and screen owner types for activities and activity
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Squash On Green

#482 feat: Add activity context module
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#483 feat: add selected suggested filter event
  .vscode/settings.json
  src/Schema/Events/Click.ts
  src/Schema/Events/ImpressionTracking.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced
