Repository artsy/cohesion, pull requests merged in 2025-04, with the labels that each got.

#576 feat(ONYX-1646): add tracking events favorites
  src/Schema/Events/ArtworkLists.ts
  src/Schema/Events/Favorites.ts
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced

#577 chore(ONYX-1646): follows tracking followup
  src/Schema/Events/Favorites.ts
  src/Schema/Events/Tap.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced, Squash On Green

#578 chore: adjust types for the favorites tab tracking
  src/Schema/Events/ArtworkLists.ts
  src/Schema/Events/Favorites.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor, Squash On Green

#579 feat(DIA-1252): add tappedShare event
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#580 feat(DIA-1283): add swipedUp event
  src/Schema/Events/Swipe.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#581 chore: add OwnerType.artworkList to ScreenOwnerType
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced, Squash On Green

#584 feat(artwork-filter): Add CmsArtworkFilter events
  src/Schema/CMS/Events/ArtworkFilter.ts
  src/Schema/CMS/Events/index.ts
  src/Schema/CMS/Values/CmsContextModule.ts
Labels: Version: Minor, Jira Synced

#585 fix(artwork-filter): fix prop
  src/Schema/CMS/Events/ArtworkFilter.ts
Labels: Version: Patch

#586 feat: Migrate SubmittedOffer and SubmittedOrder
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#587 feat(uploads2): Add events
  src/Schema/CMS/Events/UploadArtworkFlow.ts
  src/Schema/CMS/Values/CmsContextModule.ts
Labels: Version: Minor
