Repository artsy/cohesion, pull requests merged in 2025-03, with the labels that each got.

#567 feat: share lists tracking events
  src/Schema/Events/ArtworkLists.ts
  src/Schema/Events/Share.ts
  src/Schema/Events/index.ts
Labels: Version: Minor

#568 chore: add favorites as tab type
  src/DeprecatedHelpers/Tap/__tests__/TappedTabBar.test.ts
  src/Schema/Values/Tab.ts
Labels: Version: Minor

#566 feat: add tracking data for long press and create alert
  src/Schema/Events/ImpressionTracking.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor, Jira Synced

#562 feat(imports): Add CmsBatchImport events
  src/Schema/CMS/Events/BatchImportFlow.ts
  src/Schema/CMS/Events/index.ts
  src/Schema/CMS/Values/CmsContextModule.ts
  src/Schema/CMS/Values/CmsOwnerType.ts
  src/Schema/index.ts
Labels: Version: Minor, canary

#570 feat: add new OwnerType values to track existing account/settings screens
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced

#571 feat: add interface for TappedMenuItemGroup event
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor

#575 chore: Rename wallet type field and correct example values
  src/Schema/Events/Click.ts
  src/Schema/Events/ImpressionTracking.ts
Labels: Version: Minor, Jira Synced
