Repository artsy/cohesion, pull requests merged in 2025-05, with the labels that each got.

#588 chore: add collect screen owner type
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor

#589 chore: Add DarkModeOptionUpdated event
  src/Schema/Events/Settings.ts
  src/Schema/Events/index.ts
Labels: Version: Minor

#593 feat: add missing events for new profile and myc - TappedMyCollection interface
  src/Schema/Events/MyCollection.ts
  src/Schema/Events/index.ts
Labels: Jira Synced, Squash On Green

#595 feat(settingsV2): Adds new events for PartnerLocation edit and new
  src/Schema/CMS/Events/SettingsFlow.ts
  src/Schema/CMS/Events/index.ts
  src/Schema/CMS/Values/CmsContextModule.ts
Labels: Jira Synced
