Repository artsy/cohesion, pull requests merged in 2025-02, with the labels that each got.

#553 chore: Add click event for saving an artwork in CMS edit form AMBER-1268
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
Labels: Version: Minor, Merge On Green

#554 feat: add tapped navigation pills group
  .tool-versions
  src/Schema/Events/FilterAndSort.ts
  src/Schema/Events/ImpressionTracking.ts
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/EntityModuleType.ts
Labels: Version: Minor, Jira Synced, canary

#555 feat(EMI-2276): shipping estimate widget tracking
  src/Schema/Events/Click.ts
  src/Schema/Events/ImpressionTracking.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#557 feat(EMI-2276): adding estimate_available for when widget fails
  src/Schema/Events/ImpressionTracking.ts
Labels: Version: Minor, Jira Synced

#558 feat(EMI-2258): add ClickedMakeOffer to events schema for signal tracking
  src/DeprecatedSchema/DeprecatedValues.ts
  src/Schema/Events/Click.ts
  src/Schema/Events/index.ts
Labels: Version: Minor, Jira Synced

#559 feat: tracking for infinite discovery
  src/Schema/Events/Swipe.ts
  src/Schema/Events/Tap.ts
  src/Schema/Events/index.ts
  src/Schema/Values/ContextModule.ts
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced

#560 fix: add YourMaxBid owner type
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced

#561 fix: add ConfirmYourBid owner type
  src/Schema/Values/OwnerType.ts
Labels: Version: Minor, Jira Synced
