Repository artsy/cohesion, pull requests merged in 2025-06, with the labels that each got.

#602 feat(show): Add CMS Show events
  src/Schema/CMS/Events/ShowFlow.ts
  src/Schema/CMS/Events/index.ts
  src/Schema/CMS/Values/CmsContextModule.ts
Labels: Version: Minor

#603 feat: Adds more custom events for BulkEdits
  src/Schema/CMS/Events/BulkEditFlow.ts
  src/Schema/CMS/Events/index.ts
Labels: Version: Minor, Jira Synced

#604 fix(bulk-edits): Adds more consistent typing for number typed values
  src/Schema/CMS/Events/BulkEditFlow.ts
Labels: Version: Patch, Jira Synced

#606 feat: Adds artwork_ids metadata to processing and shortlist bulk edit events
  src/Schema/CMS/Events/BulkEditFlow.ts
Labels: Version: Minor, Jira Synced

#608 feat(DIA-1363): add optional destination_path field to TappedEntityGroup
  src/Schema/Events/Tap.ts
Labels: Version: Minor, Jira Synced
